In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_arr =  np.array(data)
x_np = torch.from_numpy(np_arr)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [6]:
torch.rand_like(x_data, dtype=float)

tensor([[0.9930, 0.0457],
        [0.0243, 0.7690]], dtype=torch.float64)

In [7]:

shape=(2,3)
torch.rand(shape)


tensor([[0.8682, 0.5814, 0.4023],
        [0.4158, 0.6432, 0.7407]])

In [8]:
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
tensor = torch.rand(3,4)

In [11]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [12]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [14]:
torch.cat([tensor,tensor], dim=1)

tensor([[0.6088, 0.2865, 0.0245, 0.7573, 0.6088, 0.2865, 0.0245, 0.7573],
        [0.9112, 0.6498, 0.6280, 0.1583, 0.9112, 0.6498, 0.6280, 0.1583],
        [0.3295, 0.0139, 0.0592, 0.9407, 0.3295, 0.0139, 0.0592, 0.9407]])

In [16]:
tensor @ tensor.T

tensor([[1.0269, 0.8763, 0.9185],
        [0.8763, 1.6720, 0.4954],
        [0.9185, 0.4954, 0.9973]])

In [17]:
tensor.matmul(tensor.T)

tensor([[1.0269, 0.8763, 0.9185],
        [0.8763, 1.6720, 0.4954],
        [0.9185, 0.4954, 0.9973]])

In [18]:
tensor * tensor

tensor([[3.7070e-01, 8.2087e-02, 6.0035e-04, 5.7353e-01],
        [8.3033e-01, 4.2230e-01, 3.9434e-01, 2.5068e-02],
        [1.0860e-01, 1.9239e-04, 3.5089e-03, 8.8498e-01]])

In [20]:
tensor.mul(tensor)

tensor([[3.7070e-01, 8.2087e-02, 6.0035e-04, 5.7353e-01],
        [8.3033e-01, 4.2230e-01, 3.9434e-01, 2.5068e-02],
        [1.0860e-01, 1.9239e-04, 3.5089e-03, 8.8498e-01]])

In [23]:
agg = tensor.sum()

In [24]:
agg.item()

5.367927074432373

In [29]:
tensor + 5, tensor.add_(5) # adding _ results in inplace

(tensor([[5.6088, 5.2865, 5.0245, 5.7573],
         [5.9112, 5.6498, 5.6280, 5.1583],
         [5.3295, 5.0139, 5.0592, 5.9407]]),
 tensor([[5.6088, 5.2865, 5.0245, 5.7573],
         [5.9112, 5.6498, 5.6280, 5.1583],
         [5.3295, 5.0139, 5.0592, 5.9407]]))

In [32]:
# convert to numpy

np_arr = tensor.numpy() # still shares the same memory, works both directions

In [34]:
tensor.sub_(2)

tensor([[3.6088, 3.2865, 3.0245, 3.7573],
        [3.9112, 3.6498, 3.6280, 3.1583],
        [3.3295, 3.0139, 3.0592, 3.9407]])

In [35]:
np_arr

array([[3.6088486, 3.2865086, 3.0245018, 3.7573195],
       [3.9112263, 3.64985  , 3.6279626, 3.15833  ],
       [3.3295412, 3.0138707, 3.0592356, 3.940732 ]], dtype=float32)